include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # avoid_print: false
    # prefer_single_quotes: true

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    lines-of-code: 100
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - long-method
    - long-parameter-list